# Generated by Django 5.1.7 on 2025-04-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('pdf', 'PDF Document')], max_length=10)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('processed_file', models.FileField(blank=True, null=True, upload_to='processed_documents/%Y/%m/%d/')),
                ('processing_time', models.FloatField(help_text='Processing time in seconds')),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Document Scan',
                'verbose_name_plural': 'Document Scans',
                'ordering': ['-scan_date'],
            },
        ),
        migrations.CreateModel(
            name='SensitiveInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('pii', 'Personal Identifiable Information'), ('credit_card', 'Credit Card'), ('passport', 'Passport'), ('driver_license', 'Driver License'), ('bank_account', 'Bank Account'), ('social_security', 'Social Security Number'), ('phone_number', 'Phone Number'), ('email', 'Email Address'), ('address', 'Physical Address'), ('medical_record', 'Medical Record'), ('other', 'Other')], max_length=20)),
                ('confidence', models.FloatField(help_text='Confidence score (0-1)')),
                ('location', models.JSONField(blank=True, help_text='Coordinates in document [x, y, width, height]', null=True)),
                ('count', models.PositiveIntegerField(default=1, help_text='Number of instances found')),
                ('redacted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Sensitive Information',
                'verbose_name_plural': 'Sensitive Information',
            },
        ),
    ]
